name: Qodana Launches

on:
  workflow_dispatch:
    inputs:
      runs:
        description: 'Runs'
        type: number
        default: 10
        required: false
      branch:
        description: 'Repository branch'
        type: string
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        env:
          RUNS: ${{ inputs.runs }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ inputs.branch }}
        run: |
          for (( i=0; i<RUNS; i++ )); do
            gh workflow run --repo "$GITHUB_REPOSITORY" Qodana --ref "$BRANCH"
          done
