name: Qodana
permissions: {}
on: [ push, pull_request ]

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  JAVA_VERSION: 11

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      actions: read
      contents: read
      security-events: write
    if: >
      github.actor != 'dependabot[bot]'
      && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false)
    steps:
      - uses: docker/login-action@v3
        with:
          registry: registry.jetbrains.team
          username: ${{ secrets.SPACE_USERNAME }}
          password: ${{ secrets.SPACE_PASSWORD }}
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            registry.jetbrains.team:443
            api.adoptium.net:443
            api.foojay.io:443
            api.github.com:443
            auth.docker.io:443
            caffeine.gradle-enterprise.cloud:443
            docs.oracle.com:443
            download.jetbrains.com:443
            download-cdn.jetbrains.com:443
            downloads.gradle.org:443
            downloads.gradle-dn.com:443
            errorprone.info:443
            github.com:443
            guava.dev:443
            jcenter.bintray.com:443
            jspecify.dev:443
            lightbend.github.io:443
            objects.githubusercontent.com:443
            packages.jetbrains.team:443
            pkg-cdn.jetbrains.team:443
            plugins.gradle.org:443
            plugins.jetbrains.com:443
            plugins-artifacts.gradle.org:443
            prod.fus.aws.intellij.net:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            repo.gradle.org:443
            repo.maven.apache.org:443
            repo1.maven.org:443
            resources.jetbrains.com:443
            services.gradle.org:443
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Build
        uses: ./.github/actions/run-gradle
        with:
          java: ${{ env.JAVA_VERSION }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          arguments: check -x test
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@main # v2024.3.4
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          upload-result: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@1b549b9259bda1cb5ddde3b41741a82a2d15a841 # v3.28.13
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
