name: Qodana Launches

on:
  workflow_dispatch:
    inputs:
      runs:
        description: 'Runs'
        type: number
        default: 10
        required: false

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        env:
          RUNS: ${{ inputs.runs }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for (( i=0; i<RUNS; i++ )); do
            gh workflow run --repo "$GITHUB_REPOSITORY" Qodana --ref 251-investigation
          done
